In [3]:
from safetensors.torch import load_file

In [5]:
sf_t = load_file("../data/Track00001/mix.safetensors")
latent = sf_t['latents']

In [6]:

latent.shape

torch.Size([1, 64, 1024])

In [7]:
latent[0,1,:]

tensor([-1.9830, -1.2921, -0.9089,  ..., -2.7601, -1.5248, -1.6257])

In [8]:
from vector_quantize_pytorch import FSQ

In [ ]:
FSQ()

In [ ]:
quantizer = FSQ(
    levels = [8, 5, 5, 5], # len of this is the bottlneck dimension/channels -- product of total codes 
    channel_first=True
)


In [32]:
quantizer(latent)

AssertionError: expected dimension of 4 but found dimension of 64

In [43]:
import torch
x = torch.randn(1, 4, 500) 

In [44]:
x

tensor([[[-0.3625,  0.7183,  0.5512,  ..., -1.5676,  0.3226,  0.1560],
         [ 0.7164,  1.4226, -0.0531,  ...,  1.5733, -0.1926, -0.4056],
         [-1.3205, -0.0372,  1.3850,  ..., -0.5245, -0.7346, -0.2232],
         [ 0.2902,  0.4099, -0.3767,  ...,  0.4288, -0.8736, -1.1047]]])

In [45]:

x.shape

torch.Size([1, 4, 500])

In [46]:
quantizer(x)

(tensor([[[-0.2500,  0.5000,  0.5000,  ..., -1.0000,  0.2500,  0.2500],
          [ 0.5000,  1.0000,  0.0000,  ...,  1.0000,  0.0000, -0.5000],
          [-1.0000,  0.0000,  1.0000,  ..., -0.5000, -0.5000,  0.0000],
          [ 0.5000,  0.5000, -0.5000,  ...,  0.5000, -0.5000, -1.0000]]]),
 tensor([[627, 718, 382, 218, 386, 736, 610, 379, 839, 505, 253, 641, 702, 977,
          250, 444, 581, 750, 673, 212, 681, 440, 185, 904, 649, 411, 248, 212,
          558, 524, 486, 413,  12, 139, 726, 178, 108, 206, 424, 943, 278, 801,
          190, 488, 537, 322, 657, 659, 264, 875, 310, 339, 994,  26, 846, 794,
          816, 926, 542,  13, 185, 609, 707, 265,   4, 493, 471, 471, 502, 214,
          371, 418,  73, 345, 201, 627, 751, 529, 308, 621, 580, 222, 906, 332,
          545, 303, 350, 340, 224, 286, 519, 906, 593, 983,  99, 249, 191, 555,
          293, 475,  83, 749, 457, 230, 344, 479, 673, 286, 305, 597, 817,  48,
            9, 703, 280, 145, 797, 252, 137, 308,  58, 394, 700, 495,

In [47]:
xhat, indices = quantizer(x)

In [48]:
xhat

tensor([[[-0.2500,  0.5000,  0.5000,  ..., -1.0000,  0.2500,  0.2500],
         [ 0.5000,  1.0000,  0.0000,  ...,  1.0000,  0.0000, -0.5000],
         [-1.0000,  0.0000,  1.0000,  ..., -0.5000, -0.5000,  0.0000],
         [ 0.5000,  0.5000, -0.5000,  ...,  0.5000, -0.5000, -1.0000]]])

In [23]:
quantizer.indices_to_codes(indices)

tensor([[[ 0.2500, -0.5000, -1.0000,  0.5000],
         [ 0.2500, -0.5000,  0.5000, -0.5000],
         [-0.2500, -1.0000, -0.5000,  0.5000],
         ...,
         [ 0.5000, -1.0000, -0.5000,  1.0000],
         [ 0.0000,  0.5000,  1.0000, -1.0000],
         [-0.7500, -1.0000, -1.0000,  1.0000]]])